sensor: amb3r
depth_space: log
depth_in_global: true
depth_in_local: false
sigma: 0.05
huber_scale: 2.0
shared_scale: true
per_image_scale: false
per_image_shift: false
prior_sigma_alpha: null
prior_sigma_beta: null
alpha_init: median
